---
AWSTemplateFormatVersion: '2010-09-09'
Description: CodeDeploy Deploy Mainframe Code into Micro Focus Enterprise Test Server

Parameters:
  ApplicationName:
    Type: String
    Default: mainframe-cobol-cicd-aws-microfocus
    Description: CodeDeploy Application Name

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref ApplicationName

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Join ["", [ Ref: ApplicationName, "-dg"] ]
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
  
