---
  AWSTemplateFormatVersion: "2010-09-09"

  Description: Solution Mainframe COBOL CICD AWS MicroFocus
  Parameters:
    BucketName:
      Type: String
      Description: S3 bucket name that hosts the cloudformation templates
    VPCName:
      Type: String
      Default: mainframe-cobol-cicd-aws-microfocus
    SourceRepositoryName:
      Type: String
      Default: mainframe-cobol-cicd-aws-microfocus
    EcrRepositoryName:
      Type: String
      Default: microfocus-build-tool
      Description: ECR Repository Name for Micro Focus Enterprise Developer Build Tools
    

  Resources:
    VPC:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters: 
          VPCName: !Ref VPCName
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: VPC
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/vpc.yaml"
        TimeoutInMinutes: 15
    EnterpriseDeveloperWorkstation:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          VPC: !GetAtt VPC.Outputs.VPCId
          PrivateSubnetId: !GetAtt VPC.Outputs.PrivateSubnet0
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: "Enterprise Developer Instance"
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/enterprise-developer-instance.yaml"
        TimeoutInMinutes: 15
    CodeRepository:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          RepositoryName: !Ref SourceRepositoryName
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/codecommit.yaml"
        TimeoutInMinutes: 15
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: Source Code Repository    
    CicdPipeline:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          SourceRepositoryName: !Ref SourceRepositoryName
          EcrRepositoryName: !Ref EcrRepositoryName
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/cicd-pipeline.yaml"
        TimeoutInMinutes: 15
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: CICD pipeline     
    EnterpriseTestServer:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          VPC: !GetAtt VPC.Outputs.VPCId
          PrivateSubnetId: !GetAtt VPC.Outputs.PrivateSubnet0
          ArtifactBucketName: !GetAtt CicdPipeline.Outputs.ArtifactS3BucketName
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: "Enterprise Test Server"
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/enterprise-test-server.yaml"
        TimeoutInMinutes: 15                  
    EcrRepository:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          RepositoryName: !Ref EcrRepositoryName
          CodeBuildIAMRoleArn: !GetAtt "CicdPipeline.Outputs.CodeBuildRoleArn"
        TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/ecr.yaml"
        TimeoutInMinutes: 15
        Tags:
        - Key: Solution
          Value: mainframe-cobol-cicd-aws-microfocus
        - Key: Stack
          Value: Micro Focus Build Tool ECR Repository
